# Generated by Django 5.0.2 on 2024-04-13 15:48

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mod', models.DateTimeField(auto_now=True, verbose_name=django.contrib.auth.models.User)),
                ('phoneno', models.CharField(max_length=10)),
                ('addr', models.TextField(max_length=100)),
                ('city', models.TextField(max_length=50)),
                ('pin', models.CharField(max_length=15)),
                ('oldcart', models.CharField(blank=True, max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
